name: backendRelease

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v1
    - uses: michaelw90/PHP-Lint@master
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: BackendRelease
        path: ./

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
